name: elaenv  # 環境の名前
channels:
  - defaults  # condaのデフォルトチャンネル
dependencies:
  - python=3.10  # Pythonのバージョン
  - pandas
  - matplotlib
  - seaborn
  - networkx
  - lightgbm
  - shap
  - pip  # pipをインストール
  - pip:
    - torch  # pipでインストールするパッケージ
    - optuna
