name: elaenv  # 環境の名前
channels:
  - defaults  # condaのデフォルトチャンネル
dependencies:
  - python=3.10  # Pythonのバージョン
  - pandas=2.2.3
  - matplotlib=3.10.0
  - seaborn=0.13.2
  - networkx=3.4.2
  - lightgbm=4.5.0
  - shap=0.46.0
  - pip  # pipをインストール
  - pip:
    - torch==2.6.0  # pipでインストールするパッケージ
    - optuna==4.2.0
